import styles from "./page.module.css";

export default function Extraction() {
  return (
    <main className={styles.main}>
      <div className={styles.container}>
        <table>
          <thead className={styles.tablehead}>
            <tr>
              <th>col1</th>
              <th>col2</th>
              <th>col3</th>
              <th>col4</th>
              <th>col5</th>
              <th>col6</th>
              <th>col7</th>
              <th>col8</th>
              <th>col9</th>
              <th>col10</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
            <tr>
              <td>data1</td>
              <td>data2</td>
              <td>data3</td>
              <td>data4</td>
              <td>data5</td>
              <td>data6</td>
              <td>data7</td>
              <td>data8</td>
              <td>data9</td>
              <td>data10</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  );
}
